=== BulkSecurityGeneratorProject/ExpertSystem/src/main/java/com/bru/jhipster/expertsystem/jaxb/expert_system.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="expert_system">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="question" type="question" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="question">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="answer" type="answer" nillable="true" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="answer">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="conclusion" type="conclusion" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="conclusion">
        <xs:sequence>
            <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="question" type="question" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BulkSecurityGeneratorProject/ExpertSystem/src/test/resources/loader/BlueBall.xml
<?xml version="1.0" encoding="UTF-8" ?>
<expert_system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="expert_system.xsd">
    <question>
        <text>
            What color is the ball?
        </text>
        <answer>
            <text>
                Blue.
            </text>
            <conclusion>
                <text>
                    Blue ball!
                </text>
            </conclusion>
        </answer>
        <answer>
            <text>
                Red.
            </text>
            <conclusion>
                <question>
                    <text>
                        Really?
                    </text>
                    <answer>
                        <text>
                            Yes.
                        </text>
                        <conclusion>
                            <text>
                                Red ball!
                            </text>
                        </conclusion>
                    </answer>
                    <answer>
                        <text>
                            No.
                        </text>
                        <conclusion>
                            <text>
                                Idiot.
                            </text>
                        </conclusion>
                    </answer>
                </question>
            </conclusion>
        </answer>
    </question>
</expert_system>
